name: Build & Push Docker Image

on:
  push:
    tags:
      - 'v*'   # ✅ Runs ONLY when you push a tag like v1, v1.2, v2.0.0

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Extract Git tag name (remove refs/tags/)
      - name: Extract Git Tag
        id: vars
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      # 3️⃣ Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4️⃣ Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 5️⃣ Build & push Docker image with Git tag
      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            aungmyomyat/argocd_test:${{ env.TAG }}
            aungmyomyat/argocd_test:latest
